FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip

RUN docker-php-ext-install pdo pdo_mysql

RUN pecl install redis \
    && docker-php-ext-enable redis

COPY . /var/www/api
WORKDIR /var/www/api

EXPOSE 9000
CMD ["php", "-S", "0.0.0.0:9000"]
